FROM node:18-alpine
WORKDIR /app

COPY package*.json ./
RUN npm install && npm cache clean --force

COPY . .

RUN npx prisma generate

RUN mkdir -p /app/logs

EXPOSE 4000

# Starting both the app and workers and prisma migrations
CMD ["sh", "-c", "echo 'starting Prisma migration' && npx prisma migrate deploy && echo 'migration completed' && npm run start:workers & npm start"]