FROM node:18-alpine
WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production && npm cache clean --force

COPY . .

RUN npx prisma generate

EXPOSE 3000

# Starting both the app and workers and prisma migrations
CMD ["sh", "-c", "npx prisma migrate deploy && npm run start:workers & npm start"]