FROM node:18-alpine
WORKDIR /app

COPY package*.json ./
RUN npm install && npm cache clean --force

COPY . .

RUN npx prisma generate

RUN mkdir -p /app/logs

EXPOSE 4000

CMD ["sh", "-c", "npm run start:workers & npm start"]